version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: ./devops/Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
    command: >
      sh -c "python -m manage runserver 0.0.0.0:8000"
