---

on:
  workflow_dispatch:

jobs:
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout to github
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test echo
        run: echo Django, Unchained!
      - name: Run unit tests
        run: docker compose -f devops/docker-compose.yaml run --rm app sh -c "python3 -m manage test"



